sonar.projectKey=GusttavoMLima_kapa-protetores
sonar.organization=gusttavomlima
sonar.projectName=Kapa Protetores
sonar.sources=src,App.tsx,index.ts
sonar.exclusions=node_modules/**,.expo/**,assets/**,dist/**
sonar.sourceEncoding=UTF-8
