export const colors = {
  orange: '#F39200',
  orangeDark: '#D97A00',
  orangeSoft: '#FFF3E0',
  cream: '#FFF7EC',
  white: '#FFFFFF',
  card: '#FFFFFF',
  ink: '#1A1A1A',
  inkMuted: '#6B6B6B',
  line: '#F0E4D4',
  danger: '#E53935',
  dangerSoft: '#FDECEA',
  success: '#2F6F5E',
  successSoft: '#E4F0EC',
} as const;
